#!/bin/bash

# Never under sudo. A root fcitx5 does not get org.fcitx.Fcitx5 on your session
# bus: it dies with "Unable to request dbus name. Is there another fcitx already
# running?" the moment the dbus addon loads, and the debug config dir, the UI
# process and any recordings would be root-owned. Building into /usr needs sudo;
# this script does not.
if [ "$(id -u)" -eq 0 ]; then
    echo "debug_run.sh must run as your normal user, not under sudo." >&2
    echo "  Root cannot claim org.fcitx.Fcitx5 on your session bus." >&2
    exit 1
fi

# Configuration
BUILD_DIR="build_debug"
INSTALL_DIR="$(pwd)/install_debug"
LOG_FILE="$(pwd)/fcitx5_debug.log"

# Why this script no longer starts fcitx5 itself:
#
# On a KWin wayland session the input-method protocol is not something a process
# can connect to - KWin hands it to the input method it spawns *itself*, as an
# already-open file descriptor (the child's environment shows WAYLAND_SOCKET=<fd>
# beside the usual WAYLAND_DISPLAY). A `fcitx5 -r` started from a terminal has no
# such fd, logs "Using Wayland native input method protocol: 0" and never sees a
# single keystroke: TQ9 appears in the tray and can be selected, but no key ever
# reaches the engine so the floating UI is never triggered.
#
# So we ask KWin to spawn the debug build for us: point kwinrc's InputMethod= at
# a generated .desktop whose Exec is a wrapper that sets the debug environment
# and execs fcitx5. KWin then treats it exactly like the system input method, fd
# included. The previous value is put back on exit.
if ! qdbus6 org.kde.KWin /KWin > /dev/null 2>&1; then
    echo "This script drives KWin's input-method slot over D-Bus, and KWin is" >&2
    echo "not answering (org.kde.KWin). Outside a KDE wayland session a plain" >&2
    echo "'fcitx5 -r' from a terminal works on its own - no wrapper needed." >&2
    exit 1
fi

# 1. Build
echo "Building project..."
cmake -B "$BUILD_DIR" -S . \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
    -DCMAKE_BUILD_TYPE=Debug

if [ $? -ne 0 ]; then
    echo "CMake configuration failed."
    exit 1
fi

cmake --build "$BUILD_DIR" --target install -j$(nproc)

if [ $? -ne 0 ]; then
    echo "Build failed."
    exit 1
fi

# 2. Locate paths
# Find where the lib was installed (lib, lib64, etc.)
LIB_PATH=$(find "$INSTALL_DIR" -name "libtq9.so" | xargs dirname)
SHARE_PATH="$INSTALL_DIR/share"

if [ -z "$LIB_PATH" ]; then
    echo "Error: Could not find installed library."
    exit 1
fi

# 3. Setup Environment for Debugging
# A temp config dir so the debug session never touches the real one.
CONFIG_DIR="$INSTALL_DIR/config"
mkdir -p "$CONFIG_DIR/fcitx5"
mkdir -p "$INSTALL_DIR/cache"

# These are NOT exported into this shell - they are baked into the wrapper
# script below and reach the debug fcitx5 only. Leaking PATH here previously
# caused the system fcitx5 (old addon) to spawn the freshly built UI binary - a
# half-old, half-new hybrid that is very hard to debug(非常難除錯).
DEBUG_ENV=(
    "XDG_DATA_HOME=$SHARE_PATH"
    "XDG_DATA_DIRS=$SHARE_PATH:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
    "XDG_CONFIG_HOME=$CONFIG_DIR"
    "XDG_CACHE_HOME=$INSTALL_DIR/cache"
    "PATH=$INSTALL_DIR/bin:$PATH"
    "FCITX_ADDON_DIRS=$LIB_PATH:/usr/lib/x86_64-linux-gnu/fcitx5"
)

# Pre-configure profile to enable our input method
cat > "$CONFIG_DIR/fcitx5/profile" <<EOF
[Groups/0]
# Group Name
Name=Default
# Layout
Default Layout=us
# Default Input Method
DefaultIM=tq9

[Groups/0/Items/0]
# Name
Name=tq9
# Layout
Layout=

[Groups/0/Items/1]
# Name
Name=keyboard-us
# Layout
Layout=

[GroupOrder]
0=Default
EOF

# 4. Generate the wrapper KWin will exec.
# exec, not a plain call: the WAYLAND_SOCKET fd must survive into fcitx5, and
# -D keeps it in the foreground so KWin owns the process it started. The old
# custom-input addon still sits in /usr and would otherwise load beside tq9 as a
# second copy of the same engine.
WRAPPER="$INSTALL_DIR/bin/fcitx5-debug"
DESKTOP_FILE="$INSTALL_DIR/share/applications/tq9-debug.desktop"
PID_FILE="$INSTALL_DIR/fcitx5-debug.pid"
mkdir -p "$(dirname "$DESKTOP_FILE")"
rm -f "$PID_FILE"

{
    echo '#!/bin/bash'
    echo '# Generated by debug_run.sh - regenerated on every run, do not edit.'
    printf 'echo $$ > %q\n' "$PID_FILE"
    printf 'exec > %q 2>&1\n' "$LOG_FILE"
    printf 'exec env'
    printf ' %q' "${DEBUG_ENV[@]}"
    printf ' /usr/bin/fcitx5 -r -D --disable custom-input\n'
} > "$WRAPPER"
chmod +x "$WRAPPER"

# X-KDE-Wayland-VirtualKeyboard is what marks this as an input method to KDE;
# the rest mirrors org.fcitx.Fcitx5.desktop.
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Name=TQ9 (debug build)
Comment=Debug input method started by debug_run.sh
Exec=$WRAPPER
Icon=fcitx
Terminal=false
Type=Application
NoDisplay=true
StartupNotify=false
X-KDE-StartupNotify=false
X-KDE-Wayland-VirtualKeyboard=true
X-KDE-Wayland-Interfaces=org_kde_plasma_window_management
EOF

# 5. Take over KWin's input-method slot.
OLD_IM=$(kreadconfig6 --file kwinrc --group Wayland --key InputMethod)

# A run that was killed before its cleanup leaves our own entry in kwinrc.
# Saving that as "the previous value" would make cleanup restore the debug
# build as the session's permanent input method.
if [ "$OLD_IM" = "$DESKTOP_FILE" ]; then
    echo "kwinrc still points at this script's entry - a previous run did not"
    echo "clean up. Falling back to the system input method."
    if [ -f /usr/share/applications/org.fcitx.Fcitx5.desktop ]; then
        OLD_IM=/usr/share/applications/org.fcitx.Fcitx5.desktop
    else
        OLD_IM=""
    fi
fi

# Always delete before writing: KConfig emits the notify signal kick_kwin
# depends on only when the value actually changes, so re-writing the value
# already on disk is a silent no-op.
set_input_method() {
    kwriteconfig6 --file kwinrc --group Wayland --key InputMethod --notify --delete
    if [ -n "$1" ]; then
        kwriteconfig6 --file kwinrc --group Wayland --key InputMethod --notify "$1"
    fi
}

# Two separate things have to happen, and missing either one silently leaves
# the *installed* /usr build running while everything above looks like it
# worked:
#
#   1. KWin must notice kwinrc changed at all. It watches the file through
#      KConfigWatcher, which listens for the org.kde.kconfig.notify D-Bus
#      signal - a signal kwriteconfig6 only emits with --notify. A plain
#      kwriteconfig6 updates the file on disk and KWin never re-reads it, so
#      /KWin reconfigure re-parses a config KWin already believes it has and
#      InputMethod= keeps its value from session start. (KConfig also skips the
#      signal when the value written equals the one already there.)
#   2. KWin must then restart the input method, which it does when the virtual
#      keyboard is toggled off and on - hence the flip.
#
# Step 2 without step 1 restarts the *old* command: that is exactly the
# "已安裝好的舊版" symptom, and the debug log stays empty because the wrapper
# was never executed.
kick_kwin() {
    qdbus6 org.kde.KWin /KWin reconfigure > /dev/null 2>&1
    sleep 1
    qdbus6 org.kde.KWin /VirtualKeyboard \
        org.kde.kwin.VirtualKeyboard.enabled false > /dev/null 2>&1
    sleep 1
    qdbus6 org.kde.KWin /VirtualKeyboard \
        org.kde.kwin.VirtualKeyboard.enabled true > /dev/null 2>&1
}

CLEANED=0
cleanup() {
    # Guard against Ctrl+C being pressed several times.
    [ "$CLEANED" -eq 1 ] && return
    CLEANED=1

    echo ""
    echo "Restoring KWin's input method..."
    # An unset OLD_IM means KDE Virtual Keyboard = None; leaving our entry
    # behind would silently keep the debug build as the session's input method.
    set_input_method "$OLD_IM"
    kick_kwin

    # KWin stops the process it started, but insist if something hung on to it.
    if [ -f "$PID_FILE" ]; then
        DEBUG_PID=$(cat "$PID_FILE")
        for _ in 1 2 3 4 5 6 7 8 9 10; do
            kill -0 "$DEBUG_PID" 2>/dev/null || break
            sleep 0.2
        done
        kill -9 "$DEBUG_PID" 2>/dev/null
        rm -f "$PID_FILE"
    fi

    [ -n "$TAIL_PID" ] && kill "$TAIL_PID" 2>/dev/null

    if [ -n "$OLD_IM" ]; then
        echo "Input method restored to: $OLD_IM"
    else
        echo "Input method left unset, as it was before this run."
        echo "  (System Settings > Keyboard > Virtual Keyboard to pick one.)"
    fi
}

# INT/TERM must exit, not fall through to the rest of the script.
trap 'cleanup; exit 0' INT TERM
trap cleanup EXIT

echo "----------------------------------------------------------------"
echo "Handing KWin the debug input method..."
echo "Environment baked into $WRAPPER:"
printf '  %s\n' "${DEBUG_ENV[@]}"
echo ""
echo "STT settings/logs for this session live in:"
echo "  $CONFIG_DIR/fcitx5/tq9/"
echo "Logs are being written to $LOG_FILE"
echo "----------------------------------------------------------------"

: > "$LOG_FILE"
set_input_method "$DESKTOP_FILE"
kick_kwin

# Tail logs in background
tail -f "$LOG_FILE" &
TAIL_PID=$!

# The one line that says this instance really is the compositor's input method.
# Without it nothing you type can ever reach fcitx5, and TQ9 looks dead.
STARTED=0
for _ in $(seq 1 30); do
    sleep 1
    if grep -q "Using Wayland native input method protocol: 1" "$LOG_FILE"; then
        STARTED=1
        break
    fi
    if grep -q "Using Wayland native input method protocol: 0" "$LOG_FILE"; then
        break
    fi
done

echo ""
if [ "$STARTED" -eq 1 ]; then
    echo "================================================================"
    echo "[CHECK] Input-method protocol bound - the debug build is live."
    echo "  Type in any window; TQ9 should be the active input method."
    echo "================================================================"
else
    echo "================================================================"
    echo "[CHECK] The debug instance did not report a bound input-method"
    echo "  protocol within 30s. See the log above - if it is empty, KWin"
    echo "  never started $WRAPPER at all."
    echo "================================================================"
fi

echo ">>> PRESS ENTER (or Ctrl+C) TO STOP DEBUGGING <<<"
read -r

# Normal exit path; the EXIT trap does the actual cleanup.
exit 0
